### ISSUE TITLE
'pm:dragend' event...

### ISSUE THREAD

**Issue by muenger** [Falke-Design/PMDrag#1]
Hi -- Thank you for this wonderful addition to geoman! I noticed that - if LayerGroup is selected - the 'pm:dragend' event fires twice on polygons, circles, circleMarkers etc. **twice**, but fails to fire on markers... any chance to fix this? Many thanks!

**Comment by Falke-Design** [comment]
@muenger it should be fixed, please test it and give me feedback

**Comment by muenger** [comment]
Thanks! The events now only fire once, which is great! Unfortunately, however, the markers' events still do not fire. I set up a [fiddle](https://jsfiddle.net/muenger/ae5ptqfg/) (possibly a very clunky one, as I am new to this...). Check the console and you see that only polygons, circleMarkers etc. fire an event...

**Comment by Falke-Design** [comment]
@muenger I fixed this too, please test it

**Comment by muenger** [comment]
Works perfectly! Many thanks!
